export const NORMAL    = 'normal' // 0
export const BOLD      = 'bold' // 1 - 21
export const DIM       = 'dim' // 2 - 22
export const ITALIC    = 'italic' // 3 - 23
export const UNDERLINE = 'underline' // 4 - 24
export const BLINK     = 'blink' // 5 - 25
export const INVERSE   = 'inverse' // 7 - 27
export const HIDE      = 'hide' // 8 - 28
export const STRIKE    = 'strike' // 9 - 29