export { Pres, Pres as Preset }                               from './src/Pres.js'
export { Presm }                                              from './src/Presm.js'
export { demo, randPres, randPres as randPreset }             from './src/preset-utils.js'
export { render, rgbToHsl, hslToInt, hexOntoHsl, hexOntoRgb } from './src/algebra.js'
export { scale, limFF }                                       from './src/color-utils.js'