export { fluo }        from './src/beta/fluo'
export { fluoMatrix }  from './src/alpha/fluoMatrix'
export { fluoRows }    from './src/alpha/fluoRows'
export { fluoColumns } from './src/alpha/fluoColumns'
export { fluoMat }     from './src/beta/fluoMat'
