export { degreesByColors } from './src/degreesByColors'
export { palettCrostab }   from './src/palettCrostab'
export { meta }            from './src/meta'
export { ColorGroups }     from './resources/ColorGroups'
export { Degrees }         from './resources/Degrees'
