export { RGB }                   from './src/extends/RGB.js'
export { HSL }                   from './src/extends/HSL.js'
export { rhodoneaFolios }        from './src/rhodoneaFolios'
export { Gradient }              from './src/Gradient'
export { Munsell }               from './src/Munsell.js'
export { Cova, Cova as Cuvette } from './src/Cova.js'
export { FASHIONS }              from './resources/Pavtone.Fashions'
export { PRODUCTS }              from './resources/Pavtone.Products'
export { BOOK, BOOK as TCX }     from './resources/BOOK.js'
export { LOTONE }               from './resources/LOTONE.js'
export { MIDTONE }              from './resources/MIDTONE.js'
