export { Cards, Cards as Palett } from './src/Cards'
export { red as Red } from './src/colors/red'
export { pink as Pink } from './src/colors/pink'
export { purple as Purple } from './src/colors/purple'
export { deepPurple as DeepPurple } from './src/colors/deepPurple'
export { indigo as Indigo } from './src/colors/indigo'
export { blue as Blue } from './src/colors/blue'
export { lightBlue as LightBlue } from './src/colors/lightBlue'
export { cyan as Cyan } from './src/colors/cyan'
export { teal as Teal } from './src/colors/teal'
export { green as Green } from './src/colors/green'
export { lightGreen as LightGreen } from './src/colors/lightGreen'
export { lime as Lime } from './src/colors/lime'
export { yellow as Yellow } from './src/colors/yellow'
export { amber as Amber } from './src/colors/amber'
export { orange as Orange } from './src/colors/orange'
export { deepOrange as DeepOrange } from './src/colors/deepOrange'
export { brown as Brown } from './src/greys/brown'
export { blueGrey as BlueGrey } from './src/greys/blueGrey'
export { grey as Grey } from './src/greys/grey'
export { Shades } from './src/Shades'
