export { intToStr }   from './src/intToStr'
export { rgbToStr }   from './src/rgbToStr'
export { hexToStr }   from './src/hexToStr'
export { hslToStr }   from './src/hslToStr'
export { xyzToStr }   from './src/xyzToStr'
